package message

import (
	"encoding/json"
)

func (MessageAttachment) TableName() string {
	return "messages_attachments"
}

// MessageAttachment represents an image attached to a message.
// The ai field is true when the attachment was generated by the Freegle AI illustration service.
// Partners (e.g. TrashNothing) can use this to identify and selectively remove AI-generated images.
type MessageAttachment struct {
	ID           uint64          `json:"id" gorm:"primary_key"`
	Msgid        uint64          `json:"-"`
	Path         string          `json:"path"`
	Paththumb    string          `json:"paththumb"`
	Archived     int             `json:"archived"`
	Externaluid  string          `json:"externaluid"`
	Ouruid       string          `json:"ouruid"`
	Externalmods json.RawMessage `json:"externalmods"`
	AI           bool            `json:"ai" gorm:"-"`
}

// ComputeAI populates the AI field from the externalmods JSON.
func (a *MessageAttachment) ComputeAI() {
	if len(a.Externalmods) == 0 {
		return
	}
	var m struct {
		AI interface{} `json:"ai"`
	}
	if err := json.Unmarshal(a.Externalmods, &m); err != nil {
		return
	}
	switch v := m.AI.(type) {
	case bool:
		a.AI = v
	case float64:
		a.AI = v != 0
	}
}
